service: kpi-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "rds:DescribeDBInstances"
            - "rds:CreateDBInstance"
            - "rds:DeleteDBInstance"
          Resource: "arn:aws:rds:us-east-1:503474278931:db:database-1"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

custom:
  dotenv:
    path: ./${opt:stage, ''}.env

package:
  individually: true

functions:
  peopleAnalytics:
    handler: src/functions/handler.peopleAnalytics
    timeout: 6
    events:
      - httpApi:
          path: /
          method: get
    vpc:
      securityGroupIds:
        - sg-019706310087611af
      subnetIds:
        - subnet-096db7536a0def1eb

